name: twosfs
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - pip
  - python=3.8
  - snakemake=5.22
  - numpy=1.18
  - matplotlib=3.3
  - scipy
  - jupytext=1.5.0
  - jupyterlab=2.1
  - nodejs=10.13
  - pip:
      - git+https://github.com/JereKoskela/msprime@a337b63f5331a905974239869345f1d7e09cf14f#egg=msprime
