name: twosfs
channels:
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - python=3.8
  - pip
  - snakemake>=5.26
  - numpy>=1.18
  - scipy>=1.5
  - matplotlib>=3.3
  - jupytext>=1.5.0
  - jupyterlab>=2.1
  - nodejs
  - pytest
  - hypothesis
  - attrs
  - pip:
      - git+https://github.com/tskit-dev/msprime@b8f5fb60b0ca0885b7f1c2d7ac7a9ae3b95fc543#egg=msprime
      - pyslim
